name: server
version: 0.1.0.0
default-extensions:
  - OverloadedStrings
dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - '-Wall'
  - '-Werror'
library:
  source-dirs: src
executables:
  server-prod:
    main: Main.hs
    source-dirs: app/server-prod
    ghc-options:
      - '-O2'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - server